Migrate from LHAPDF 5 to LHAPDF 6
LHAPDF 6 is a complete C++ rewrite with no Fortran API, directory-based
PDF sets, and lhapdf-config for build configuration. This commit adapts
CompHEP to use LHAPDF 6 instead of the deprecated LHAPDF 5.

Build system:
- configure uses lhapdf-config (--cflags/--libs/--datadir) instead of
  LHAPDFPATH env var, writes CXX and LHAPDF_DATADIR config files
- CLIBS_BASE split: symb binaries link without libLHAPDF, num binaries
  link with full CLIBS (including -lLHAPDF -lstdc++)
- lhapdf target is now a no-op (system library, no symlinks)

Core LHAPDF integration:
- New C++ wrapper (lhapdf6_wrapper.cpp) provides extern "C" shim for
  LHAPDF 6 native API, replacing Fortran wrap.F
- New pure-C filesystem scanner (lhapdf_update.c) in libserv discovers
  installed PDF sets and updates strfuns.mdl / beams.mdl at runtime
- clhapdf.h: plain C prototypes replace cfortran.h Fortran macros
- lhapdf.c: uses lhapdf6_* API instead of PDFsets.index parsing
- sf_lhapdf.c: adapted for LHAPDF 6 name format (no .LHpdf/.LHgrid)

Runtime:
- .lhapdfpath file + LHAPDF_DATA_PATH env var replace LHAPDFPATH
- s_comphep and n_comphep call update_lhapdf_mdl() at startup
- F10 key in n_comphep GUI refreshes LHAPDF PDF list
- PDF naming: LHA:cteq6l1(proton):0:0 instead of LHA:cteq6m.LHpdf(proton):10000:0

Bug fixes:
- beams.c: beam[0] -> beam[i] in construct_full_sf_name(), fix strdup leak
- sf_lhapdf.c: info_lhapdf extra_commands index collision, LHA entry
  numbering starts from 100 to avoid PDF entry collision
- symb_batch.pl: use $strfun2 for strfun_2 output (was $strfun1)
- strfuns-lhapdf.mdl: header |> -> <|> (readtable 4th column fix)
- read_mdl.c: default mem="0" before sscanf
- lhapdf_update.c: sprintf buffer overflow fixes

Removed:
- wrap.F (Fortran wrapper, no Fortran in LHAPDF 6)
- strfun/PDFsets.index (obsolete LHAPDF 5 set index)
- doc/LHAPDF_in_CompHEP-HOWTO (obsolete LHAPDF 5 howto)

Tested: Drell-Yan p,pbar->mu+mu- @ sqrt(s)=1960 GeV with LHA:cteq6l1
gives sigma = 8.198 +/- 0.023 nb (vs 8.085 +/- 0.024 nb with built-in
PDF:cteq6l1, ~1.4% difference within statistical errors).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,7 @@ CONF_FILE_DIR=.
 CONFIG_ERROR=0
 F77=gfortran
 CC=gcc
+CXX=g++
 STDCFLAGS=
 LHAPDF=0
 LIBXML=0
@@ -58,8 +59,7 @@ if (test -n "$SHELP" ) then
   echo './configure --debug | --with-gcc3 | --with-lhapdf | --with-libxml | --optimise | --with-root | --with-m64'
   echo '    --debug       - compilation with debugging symbols'
   echo '    --with-gcc3   - shoulf be used if your gcc version is 3.X.X, FORTRAN compiler is g77 '
-  echo '    --with-lhapdf - PDF from LHAPDF will be used. The variable LHAPDFPATH should point to '
-  echo '                     a directory with lib/liblhapdf.a (set the full path!)'
+  echo '    --with-lhapdf - PDF from LHAPDF 6 will be used. lhapdf-config must be in PATH.'
   echo '    --with-libxml - mix program will use libxml2 in order to analyze and prepare HepML code'
   echo '    --optimise    - -O3 optimisation will be used'
   echo '    --with-m64    - -m64 option will be used, it is useful at 64-bit machines'
@@ -335,12 +335,15 @@ fi
 ################################################################
 if (test -n "$SLHAPDF") then
   LHAPDF=1
-  echo -n "checking for LHAPDF...  "
-  if [ x$LHAPDFPATH = x ]; then
-    echo "  configure (err): variable LHAPDFPATH is not defined. Exit"
+  echo -n "checking for LHAPDF 6...  "
+  if ! command -v lhapdf-config > /dev/null 2>&1; then
+    echo "  configure (err): lhapdf-config not found in PATH. Install LHAPDF 6 or add to PATH."
     exit 1
   fi
-  echo "found"
+  LHAPDF_CFLAGS=`lhapdf-config --cflags`
+  LHAPDF_LIBS=`lhapdf-config --libs`
+  LHAPDF_DATADIR=`lhapdf-config --datadir`
+  echo "found (datadir: $LHAPDF_DATADIR)"
 fi
 
 ################################################################
@@ -410,15 +413,17 @@ fi
 STDCFLAGS="$STDCFLAGS -DCOMPHEP"
 
 CFLAGS=""
+CLIBS_BASE="$CLIBS"
 if (test $LHAPDF = 1) then
-  CFLAGS="$CFLAGS -DLHAPDF"
+  CFLAGS="$CFLAGS -DLHAPDF $LHAPDF_CFLAGS"
   F77FLAGS="$F77FLAGS -DLHAPDF"
-  CLIBS="-L$LHAPDFPATH/lib -lLHAPDF $CLIBS"
+  CLIBS="$LHAPDF_LIBS -lstdc++ $CLIBS"
 fi
 
 if (test $LIBXML = 1) then
   CFLAGS="$CFLAGS -DLIBXML -I$LIBXMLINC"
   CLIBS="-L$LIBXMLLIB -lxml2 $CLIBS"
+  CLIBS_BASE="-L$LIBXMLLIB -lxml2 $CLIBS_BASE"
 fi
 CFLAGS="$STDCFLAGS $CFLAGS"
 
@@ -434,21 +439,30 @@ if (test -n "$SPRINT") then
   echo "RANLIB:   $RANLIB"
   echo "ROOTINC:  $ROOTINC"
   echo "ROOTLIB:  $ROOTLIB"
+  echo "LHAPDF_DATADIR: $LHAPDF_DATADIR"
   echo "======================================================="
   exit 1
 fi
 
 echo $CC       > $CONF_FILE_DIR/CC
 echo $CFLAGS   > $CONF_FILE_DIR/CFLAGS
-echo $CLIBS    > $CONF_FILE_DIR/CLIBS
+echo $CLIBS      > $CONF_FILE_DIR/CLIBS
+echo $CLIBS_BASE > $CONF_FILE_DIR/CLIBS_BASE
 
 echo $F77      > $CONF_FILE_DIR/F77
 echo $F77FLAGS > $CONF_FILE_DIR/F77FLAGS
 echo $F77LIBS  > $CONF_FILE_DIR/F77LIBS
 
+echo $CXX      > $CONF_FILE_DIR/CXX
 echo $RANLIB   > $CONF_FILE_DIR/RANLIB
 echo $ROOTINC  > $CONF_FILE_DIR/ROOTFLAGS
 echo $ROOTLIB  > $CONF_FILE_DIR/ROOTLIBS
+
+if (test $LHAPDF = 1) then
+  echo $LHAPDF_DATADIR > $CONF_FILE_DIR/LHAPDF_DATADIR
+else
+  echo "" > $CONF_FILE_DIR/LHAPDF_DATADIR
+fi
 
 echo "======================================="
 echo "User can change any compilation/linking options editting "
